# Let travis know the language it needs to run
language: python

# Mention the python version in which travis will run the app
python:
  - "3.6"


# command to install dependencies in the requirements file
# You can also install the coverage here to avoid it being in the requirements file
# It is important to avoid things like coverage, pep8 that are not required to run the app
install:
  - pip install -r requirements.txt
  - pip install coverage
  

 
script: 
  - python app.py


after_script:
  - coveralls
 
after_success:
  - codecov

